project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from simpleapp.views import multiply

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('products/', include('simpleapp.urls')), # Делаем так, чтобы все адреса из нашего приложения (simpleapp/urls.py) подключались к главному приложению с префиксом products/.
    path('multiply/', multiply),
    path("accounts/", include('allauth.urls')), # то что слева, это взамен на то что справа от данных слов. path('accounts/', include('django.contrib.auth.urls')), path('accounts/', include('accounts.urls')), СТ чтобы страница регистрации и авторизации была с возможностью авторизироваться через яндекс аккаунт


]

project/simpleapp/models.py
from django.db import models
from datetime import datetime
from django.core.validators import MinValueValidator
from django.urls import reverse
from django.contrib.auth.models import AbstractUser

class Staff(models.Model):

    director = 'DI'
    admin = 'AD'
    cook = 'CO'
    cashier = 'CA'
    cleaner = 'CL'

    POSITIONS = [
        (director, 'Директор'),
        (admin, 'Администратор'),
        (cook, 'Повар'),
        (cashier, 'Кассир'),
        (cleaner, 'Уборщик') ]

    full_name = models.CharField(max_length=255)
    position = models.CharField(max_length=2, choices=POSITIONS, default=cashier)
    labor_contract = models.IntegerField()

    def get_last_name(self):
        return self.full_name.split()[0]

class Product(models.Model):
    name = models.CharField(max_length=255, unique=True) # unique=True - названия товаров не должны повторяться
    category = models.ForeignKey(to='Category', on_delete=models.CASCADE, related_name='products') # category - поле категории будет ссылаться на модель категории. related_name='products' - все продукты в категории будут доступны через поле products
    price = models.FloatField(default=0.0, validators=[MinValueValidator(0.0)])
    quantity = models.IntegerField(validators=[MinValueValidator(0)])
    composition = models.TextField(default="Состав не указан")
    description = models.TextField(default="Описание не указано")

    def __str__(self):
        return f'{self.name.title()}: {self.description[:20]}'

    def get_absolute_url(self):
        return reverse('product_detail', args=[str(self.id)])

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class Category(models.Model): # Категория, к которой будет привязываться товар
    name = models.CharField(max_length=100, unique=True) # названия категорий тоже не должны повторяться

    def __str__(self):
        return self.name.title()

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

class Order(models.Model):
    time_in = models.DateTimeField(auto_now_add=True)
    time_out = models.DateTimeField(null=True)
    cost = models.FloatField(default=0.0)
    pickup = models.BooleanField(default=False)
    complete = models.BooleanField(default=False)
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE, related_name='orders')
    products = models.ManyToManyField(Product, through='ProductOrder')

    def finish_order(self):
        self.time_out = datetime.now()
        self.complete = True
        self.save()

    def get_duration(self):
        if self.complete:  # если завершён, возвращаем разность объектов
            return (self.time_out - self.time_in).total_seconds() / 60.0
        else:  # если ещё нет, то сколько длится выполнение
            return (datetime.now() - self.time_in).total_seconds() / 60.0

class ProductOrder(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    _amount = models.IntegerField(default=1, db_column = 'amount')


    def product_sum(self):
        product_price = self.product.price
        return product_price * self._amount

    @property
    def amount(self):
        return self._amount

    @amount.setter
    def amount(self, value):
        self._amount = int(value) if value >= 0 else 0
        self.save()

class User(AbstractUser): # СТ добавили ещё одно поле для имеила, чтобы новый пользователь мог указать больше чем один свой имеил, и получил на оба имеила приветственное письмо
    email_2 = models.EmailField()

project/templates/product.html
{% extends 'flatpages/default.html' %} <!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->

<!-- Название у нас будет Product -->
{% block title %}
Product
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
<h1>{{ product }}</h1>
{% endblock content %}

project/templates/product_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление товара</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.name }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

project/templates/product_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Товар</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

project/templates/products.html
{% extends 'flatpages/default.html' %} <!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->

{% load custom_tags %} <!-- Подключаем новый файл с нашим тегом -->
{% load custom_filters %}

{% block title %}
Products <!-- Название у нас будет products -->
{% endblock title %}
<!-- В контенте на странице мы выводим все товары -->
{% block content %}
<h1>Все товары</h1>
    <h3>{% current_time %}</h3> <!-- Используем переданную из представления переменную time_now и применяем к ней фильтр date. По назначению этот фильтр очень похож на метод strftime у объекта datetime в Python — вывод времени в указанном формате. -->
    <h3>{{ next_sale|default_if_none:"Чуть позже сообщим о распродаже!" }}</h3>
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!--Форма поиска по словам-->
<form action="" method="get" >
    {{ filterset.form.non_field_errors }}

    {{ filterset.form.name__icontains.errors }}
    <label for="{{ filterset.form.name__icontains.id_for_label }}">Search</label>
    <input
        id="{{ filterset.form.name__icontains.id }}"
        name="{{ filterset.form.name__icontains.name }}"
        value="{{ filterset.form.name__icontains.value }}"
        class="form-control"
    >
    <input type="submit" class="mt-3 btn-primary" value="Найти" />
</form>
<hr>
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<form action="" method="get"> <!-- Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе -->
   {{ filterset.form.as_p }} <!-- Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями-->
   <input type="submit" value="Найти" /><!--Добавим кнопку отправки данных формы-->
</form>

<hr>
   <!-- Выводим товары, только если они есть с помощью тега if -->
   {% if products %}
        <table> <!-- Начинаем описывать таблицу -->
                   <tr style="border: 1px solid #afabab;" bgcolor="#CAAAC5"> <!-- Добавляем строку -->
                       <td style="border: 1px solid #afabab;">Название</td> <!-- Добавляем ячейку в строку -->
                       <td style="border: 1px solid #afabab;">Описание</td> <!-- Добавляем ещё одну ячейку в строку и так далее -->
                       <td style="border: 1px solid #afabab;">Категория</td>
                       <td style="border: 1px solid #afabab;">Цена</td>
                       <td style="border: 1px solid #afabab;">Количество</td>
                       {% if perms.simpleapp.change_product %} <!--СТ если у пользователя есть разрешение на изменение, то выводим столбец, в противном случае не выводим столбец-->
                       <td style="border: 1px solid #afabab;">Изменить</td>
                       {% endif %}
                       {% if perms.simpleapp.delete_product %}
                       <td style="border: 1px solid #afabab;">Удалить</td>
                       {% endif %}
                   </tr> <!-- Не забываем закрыть HTML-тег строки -->
           {% for product in products %} <!-- Для каждого товара будете генерироваться новая строчка, т.е. новый HTML код, который указан в теле цикла. При этом сам цикл работает точно так же, как и в Python. product — переменная цикла, т.е. наш товар полученный из списка -->
                <!-- Не забываем, что переменные в шаблоне ничем не отличаются от переменных в Python. Здесь также можно получать доступ к полям объекта модели. Например, здесь мы выводим имя, в следующем столбце описание, и т.д.  -->
            <tr style="border: 1px solid #afabab;">
                <td style="border: 1px solid #afabab;">{{ product.name }}</td>
                <td style="border: 1px solid #afabab;">{{ product.description|truncatechars:15 }}</td>
                <td style="border: 1px solid #afabab;">{{ product.category.name }}</td>
                <td style="border: 1px solid #afabab;">{{ product.price|currency:"usd" }}</td>  <!-- Используем наш фильтр -->
                <td style="border: 1px solid #afabab;">{{ product.quantity }}</td>
                {% if perms.simpleapp.change_product %} <!--СТ если есть разрешение на изменение, то выводим ссылку-кнопку изменить-->
                <td style="border: 1px solid #afabab;" width="80px"><a href="{% url 'product_update' product.id %}"> Изменить </a></td> <!-- width - ширина ячейки-->
                {% endif %}
                {% if perms.simpleapp.delete_product %}
                <td style="border: 1px solid #afabab;" width="80px"><a href="{% url 'product_delete' product.id %}"> Удалить </a></td>
                {% endif %}
            </tr>
            {% endfor %}
        </table> <!-- ... и таблицы -->
   {% else %}
       <h2>Товаров нет!</h2> <!-- Если товаров нет, говорим, что товаров нет ;) -->
   {% endif %}

<!-- Добавляем пагинацию на страницу-->
       <!--Информация о предыдущих страницах-->
       {% if page_obj.has_previous %} <!--2024-08-27 19-59-13.mkv-->
           <!--Для каждой ссылки пагинации указываем обработку через новый тег-->
           <a href="?{% url_replace page=1 %}">1</a> <!-- url_replace - 2024-08-27 19-54-35.mkv-->
           {% if page_obj.previous_page_number != 1 %}
               ...
               <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
           {% endif %}
       {% endif %}


       {# Информация о текущей странице #}
       {{ page_obj.number }}


       {# Информация о следующих страницах #}
       {% if page_obj.has_next %}
           <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
           {% if paginator.num_pages != page_obj.next_page_number %}
               ...
               <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
           {% endif %}
       {% endif %} <!-- Закончили добавлять пагинацию на страницу-->

{% endblock content %}